version: "3.9"

services:
  db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3366:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: { }